SID_SESSION_CONTROL = 0x10
SID_ECU_RESET = 0x11
SID_CLEAR_DIAGNOSTIC = 0x14
SID_READ_DTC = 0x19
SID_READ_DATA = 0x22
SID_SECURITY_ACCESS = 0x27
SID_WRITE_DATA = 0x2E
SID_ROUTINE_CONTROL = 0x31
SID_TESTER_PRESENT = 0x3E

NRC_INCORRECT_LENGTH = 0x13
NRC_CONDITIONS_NOT_CORRECT = 0x22
NRC_REQUEST_OUT_OF_RANGE = 0x31
NRC_SECURITY_ACCESS_DENIED = 0x33
NRC_INVALID_KEY = 0x35
NRC_EXCEEDED_ATTEMPTS = 0x36
NRC_REQUIRED_TIME_DELAY = 0x37
NRC_SUBFUNCTION_NOT_SUPPORTED = 0x12
NRC_SERVICE_NOT_SUPPORTED_IN_SESSION = 0x7F
NRC_SUBFUNCTION_NOT_SUPPORTED_IN_SESSION = 0x7E


def positive_sid(sid: int) -> int:
    return sid + 0x40
